-- Table: public.rol

-- DROP TABLE IF EXISTS public.rol;

CREATE TABLE IF NOT EXISTS public.rol
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    activo boolean NOT NULL,
    creadoel date,
    descripcion character varying(255) COLLATE pg_catalog."default",
    nombre character varying(60) COLLATE pg_catalog."default",
    CONSTRAINT rol_pkey PRIMARY KEY (id),
    CONSTRAINT uk_43kr6s7bts1wqfv43f7jd87kp UNIQUE (nombre)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.rol
    OWNER to postgres;
    
 -- Table: public.usuario

-- DROP TABLE IF EXISTS public.usuario;

CREATE TABLE IF NOT EXISTS public.usuario
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    activo boolean NOT NULL,
    actualizadoel date,
    borrado boolean NOT NULL,
    codigouser uuid,
    creadoel date,
    email character varying(100) COLLATE pg_catalog."default",
    emailconfirmado boolean NOT NULL,
    esadministrador boolean NOT NULL,
    imagen character varying(255) COLLATE pg_catalog."default",
    nombrecompleto character varying(255) COLLATE pg_catalog."default",
    nombreusuario character varying(60) COLLATE pg_catalog."default",
    ocupacion character varying(255) COLLATE pg_catalog."default",
    password character varying(60) COLLATE pg_catalog."default",
    telefono character varying(255) COLLATE pg_catalog."default",
    telefonoconfirmado boolean NOT NULL,
    valido boolean NOT NULL,
    vencepassword date,
    CONSTRAINT usuario_pkey PRIMARY KEY (id),
    CONSTRAINT uk_5171l57faosmj8myawaucatdw UNIQUE (email),
    CONSTRAINT uk_78jlhqg2q39hqi3veumeqoo2h UNIQUE (nombreusuario)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.usuario
    OWNER to postgres;
    
    
 -- Table: public.usuario_roles

-- DROP TABLE IF EXISTS public.usuario_roles;

CREATE TABLE IF NOT EXISTS public.usuario_roles
(
    usuario_id bigint NOT NULL,
    roles_id bigint NOT NULL,
    CONSTRAINT fk861wr18rjyh6pmadvor1u36vb FOREIGN KEY (roles_id)
        REFERENCES public.rol (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkqblnumndby0ftm4c7sg6uso6p FOREIGN KEY (usuario_id)
        REFERENCES public.usuario (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.usuario_roles
    OWNER to postgres;
    
    
 -- Table: public.cliente

-- DROP TABLE IF EXISTS public.cliente;

CREATE TABLE IF NOT EXISTS public.cliente
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(255) COLLATE pg_catalog."default",
    importe double precision,
    CONSTRAINT cliente_pkey PRIMARY KEY (id),
    CONSTRAINT uk_57784ssr55556454 UNIQUE (nombre)
        INCLUDE(nombre)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.cliente
    OWNER to postgres;